
# Fix how vim shows whem opening vim in tmux and outside
# (Tmux uses 24 bit color when this is set.:
set-option -sa terminal-overrides ",xterm*:Tc"

# Make <ctrl>+<space> the new prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g status-position top
set -g history-file ~/.tmux_history

# Reload config shortcut
bind r source-file ~/.config/tmux/tmux.conf

#################################################################
# Styling without the need for plugins
#################################################################

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 100

# bg=default will make the status bar transparent
set -g status-style "fg=${gray_light},bg=default"

# #S = session name
set -g status-left "#[fg=${green_soft},bold]#h| #S #[fg=${gray_light},nobold] |"
#set -g status-right " #{cpu} 󰹪 #{mem}"

# How to format the currently active window in the status bar
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W"

# How to format the non-active window in the status bar
set -g window-status-format " #I:#W"

# Style otherwise blinky messages 
set -g message-style "fg=${gray_light},bg=default"

# Change the selection coloering
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"

# When switching panes, style inactive and active ones
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"

####################################
# Tmux plugins
####################################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
