#!/bin/bash

# This should fix the following error:
# 
#  $ gpg --card-status
#  gpg: OpenPGP card not available: Permission denied

gpgconf --kill all

# Running this helps to get things going again.
gpg --card-status